### ISSUE TITLE
Allow rawSQL for SelectTableQuery

### ISSUE THREAD

**Issue by Midnight-Coder** [krux/hyperion#383]

**Comment by realstraw** [comment]
It will be great but please first make sure AWS data pipeline allows that in the first place. http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-object-sqldatanode.html there is a required `table` field, I cannot remember what happens if the `selectQuery` field is inconsistent with the `table` field.

**Comment by realstraw** [comment]
We made `TableQuery` mainly to make sure that those two fields are consistent.

**Comment by Midnight-Coder** [comment]
A quick experiment showed this is not possible using the AWS Data Pipeline.
The [MySQLDataNode](http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-object-mysqldatanode.html) throws errors in case of table joins ({{Returning tail errorMsg :Unknown options: ..}})
--
